nome = str(input('Digite seu nome completo: ')).strip()
partes = nome.split()
print('Muito prazer em te conhecer!')
print('Seu primeiro nome é {}'.format(partes[0]))
print('Seu último nome é {}'.format(partes[-1]))